config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'main/home'
  get 'main/reports', as: :reports
  root to: 'main#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/currency.rb
# frozen_string_literal: true

class Currency < ApplicationRecord
  enum currency_type: %i[dolar uf]
  default_scope -> { order(date: :asc) }

  class << self
    def between(date1, date2, currency, formated = false)
      case currency
      when :dolar
        data = Integration::SBIF::Dolar.between(date1, date2)
      when :uf
        data = Integration::SBIF::UF.between(date1, date2)
      end
      if data && formated
        return format_data(data)
      else
        return data
      end
    end

    def set_until(date, currency)
      until_date = date
      last_currency = send(currency).last
      if last_currency
        if last_currency.date < date
          # Fill between dates
          case currency
          when :dolar
            results =  Integration::SBIF::Dolar.between(last_currency.date, date)
          when :uf
            results =  Integration::SBIF::UF.between(last_currency.date, date)
          end
          set_data(results, currency)
          return results
        end
      else # Empty db
        case currency
        when :dolar
          results =  Integration::SBIF::Dolar.before_month(date)
          results += Integration::SBIF::Dolar.by_month(date)
        when :uf
          results =  Integration::SBIF::UF.before_month(date)
          results += Integration::SBIF::UF.by_month(date)
        end
        set_data(results, currency)
        return results
      end
    end

    def set_data(results, currency)
      results.each do |result|
        next if send(currency).find_by(date: result['Fecha'])
        Currency.create(currency_type: currency,
                        date: result['Fecha'],
                        clp_value: result['Valor'].delete('.').tr(',', '.').to_f)
      end
    end

    def format_data(data)
      Hash[*data.map { |data| [data['Fecha'], data['Valor'].delete('.').tr(',', '.').to_f] }.flatten]
    end
  end
end

app/models/integration/sbif/base.rb
# frozen_string_literal: true

module Integration
  module SBIF
    class Base
      API_KEY = ENV['SBIF_KEY']
      API_BASE_URL = 'http://api.sbif.cl/api-sbifv3/recursos_api'

      class << self
        def resource_name
          name.demodulize.downcase
        end

        def resource_key_result
          "#{resource_name.upcase}s"
        end

        def by_year(date)
          resource "#{resource_name}/#{date.year}"
        end

        def by_month(date)
          resource "#{resource_name}/#{date.year}/#{format('%02d', date.month)}"
        end

        def by_day(date)
          resource "#{resource_name}/#{date.year}/#{format('%02d', date.month)}/dias/#{format('%02d', date.day)}"
        end

        def between(date1, date2)
          resource "#{resource_name}/periodo/#{date1.year}/#{date1.month}/#{date2.year}/#{date2.month}"
        end

        ## Before a date
        def before_year(date)
          resource "#{resource_name}/anteriores/#{date.year}"
        end

        def before_month(date)
          resource "#{resource_name}/anteriores/#{date.year}/#{format('%02d', date.month)}"
        end

        ## After a date
        def after_year(date)
          resource "#{resource_name}/posteriores/#{date.year}"
        end

        def after_month(date)
          resource "#{resource_name}/posteriores/#{date.year}/#{format('%02d', date.month)}"
        end

        private

        def resource(url_resource)
          result = RestClient.get "#{API_BASE_URL}/#{url_resource}?apikey=#{API_KEY}&formato=json"
          if result.code == 200
            json_result = JSON.parse(result.body)
            return json_result[resource_key_result]
          else
            raise ArgumentError, 'Invalid response'
            return nil
         end
        rescue Errno::ECONNREFUSED
          Rails.logger.error('Error trying to connect to the SBIF API')
          return nil
        rescue RestClient::NotFound
          Rails.logger.error('Contents not found in SBIF API')
          return nil
        rescue Excepcion => e
          Rails.logger.error('Something wrong happens')
          Rails.logger.error(e)
          return nil
        end
      end
    end
  end
end

app/models/integration/sbif/dolar.rb
# frozen_string_literal: true

module Integration
  module SBIF
    class Dolar < Base
      class << self
        def resource_key_result
          'Dolares'
        end
      end
    end
  end
end

app/models/integration/sbif/tmc.rb
# frozen_string_literal: true

module Integration
  module SBIF
    class TMC < Base
      class << self
        def by_day(_date)
          raise 'Invalid Method for this indicator'
        end
      end
    end
  end
end

app/models/integration/sbif/uf.rb
# frozen_string_literal: true

module Integration
  module SBIF
    class UF < Base
    end
  end
end

app/models/tmc.rb
# frozen_string_literal: true

class TMC < ApplicationRecord
  class << self
    def between(date1, date2, formated = false)
      data = Integration::SBIF::TMC.between(date1, date2)
      if data && formated
        return format_data(data)
      else
        return data
      end
    end

    def format_data(data)
      formated_data = {}
      data.each do |d|
        formated_data[d['Tipo']] ||= {}
        formated_data[d['Tipo']][:label] ||= [d['Titulo'].presence, d['SubTitulo'].presence].join(' - ')
        formated_data[d['Tipo']][:data] ||= []
        formated_data[d['Tipo']][:data] <<  [d['Fecha'], d['Valor']]
      end
      formated_data.map { |k, v| { name: v[:label], data: v[:data], type: k } }
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
# frozen_string_literal: true

class MainController < ApplicationController
  def reports
    if params[:date_range] && params[:date_range][:starts_at].presence && params[:date_range][:ends_at].presence
      @starts_at = params[:date_range][:starts_at].to_time
      @ends_at = params[:date_range][:ends_at].to_time

      # Manage special conditions
      @starts_at, @ends_at = @ends_at, @starts_at if @starts_at > @ends_at
      if @starts_at == @ends_at
        flash[:alert] = 'Las fechas no pueden ser iguales!'
        redirect_to(root_path) && return
      elsif @ends_at > Time.zone.now
        flash[:alert] = 'Las fechas no pueden ser en el futuro!'
        redirect_to(root_path) && return
      end

      @ufs = Currency.between(@starts_at, @ends_at, :uf, true)
      @dolares = Currency.between(@starts_at, @ends_at, :dolar, true)
      @tmcs = TMC.between(@starts_at, @ends_at, true)

      if @ufs.nil? && @dolares.nil? && @tmcs.nil?
        render file: "#{Rails.root}/public/404", status: :not_found && return
      end

      @points = (@ends_at - @starts_at) / 1.day <= 40
    else
      flash[:alert] = 'Rellene todos los datos antes de continuar!'
      redirect_to(root_path) && return
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def flash_class(level)
    case level
    when :notice then 'alert alert-info'
    when :success then 'alert alert-success'
    when :error then 'alert alert-danger'
    when :alert then 'alert alert-danger'
    end
  end
end

app/helpers/main_helper.rb
# frozen_string_literal: true

module MainHelper
  def data_statistic(data)
    values = data.values.map(&:to_f)
    min = values.min
    max = values.max
    avg = values.sum / values.count

    [min, max, avg]
  end

  def tmc_stats(tmcs)
    tmcs.map { |tmc| { name: tmc[:name], max: tmc[:data].map(&:last).max } }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceData</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container mt-md-5">
      
      <div class="row">
        <div class="col-md-12">
          <% flash.each do |key, value| %>
            <div class="<%= flash_class(key.to_sym) %>">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true" style="font-size:20px">×</span>
              </button>
              <%= value %>
            </div>
          <% end %>
        </div>
      </div>

      <%= yield %>

    </div>
  </body>
</html>

app/views/main/draw_report.html.erb
<div class="container mt-md-5">

  <div class="row">
    <div class="col-md-12 text-center">
      <h4>Consulta entre el <%= params[:date_range][:starts_at] %> y el <%= params[:date_range][:ends_at] %></h4>
    </div>
  </div>

  <div class="row my-md-5 card">
    <div class="col-md-12 card-body">
      <h4>UF</h4>
      <%= area_chart @ufs, thousands: ".", decimal: ",", legend: "UF" %>
      <% min, max, avg = data_statistic(@ufs) %>
    </div>
    <div class="col-md-12 text-center">
      <div class="card-body">
        Mínimo: <%=  number_with_delimiter(min, delimiter: ".", separator: "," )  %> |
        Máximo:  <%=  number_with_delimiter(max, delimiter: ".", separator: "," ) %> |
        Media: <%=  number_with_delimiter('%.2f' % avg, delimiter: ".", separator: ",", precision: 2 ) %>
      </div>
    </div>
  </div>

  <div class="row my-md-5 card">
    <div class="col-md-12 card-body">
      <h4> Dolares</h4>
      <%= area_chart @dolares, thousands: ".", decimal: ",", legend: "Dolares" %>
      <% min, max, avg = data_statistic(@dolares) %>
    </div>
    <div class="col-md-12 text-center">
      <div class="card-body">
        Mínimo: <%=  number_with_delimiter(min, delimiter: ".", separator: "," )  %> |
        Máximo:  <%=  number_with_delimiter(max, delimiter: ".", separator: "," ) %> |
        Media: <%=  number_with_delimiter('%.2f' % avg, delimiter: ".", separator: ",", precision: 2 ) %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12 text-center">
    <%= link_to t(:back), root_path, class: "btn btn-success" %>
  </div>
</div>

app/views/main/home.html.erb
<div class="row">
  <div class="col-md-7 offset-md-3 text-center pt-md-5 mt-md-5 card">
    <div class="card-body">
    <strong>Seleccione un rango de fechas para realizar la consulta</strong>
    <%= form_for :date_range, url: reports_path, method: :get do |f| %>
      <%= f.text_field :starts_at, class: "datepicker" %>
      <%= f.text_field :ends_at, class: "datepicker" %>
      <%= f.submit t(:submit), class: "btn btn-primary"  %>
    <% end %>
    </div>
  </div>
</div>

app/views/main/reports.html.erb
<div class="row">
  <div class="col-md-12 text-center">
    <h4>Consulta entre el <%= @starts_at.strftime("%d/%m/%Y") %> y el <%= @ends_at.strftime("%d/%m/%Y") %></h4>
  </div>
</div>

<div class="row my-md-5 card">
  <div class="col-md-12 card-body">
    <h4>UF</h4>
    <%= area_chart @ufs, thousands: ".", decimal: ",", points: @points, xtitle: "Período", ytitle: "CLP",  prefix: "$" %>
    <% min, max, avg = data_statistic(@ufs) %>
  </div>
  <div class="col-md-12 text-center">
    <div class="card-body">
      Mínimo: $<%=  number_with_delimiter(min, delimiter: ".", separator: "," )  %> |
      Máximo:  $<%=  number_with_delimiter(max, delimiter: ".", separator: "," ) %> |
      Media: $<%=  number_with_delimiter('%.2f' % avg, delimiter: ".", separator: ",", precision: 2 ) %>
    </div>
  </div>
</div>

<div class="row my-md-5 card">
  <div class="col-md-12 card-body">
    <h4> Dolar</h4>
    <%= area_chart @dolares, thousands: ".", decimal: ",", points: @points, xtitle: "Período", ytitle: "CLP",  prefix: "$" %>
    <% min, max, avg = data_statistic(@dolares) %>
  </div>
  <div class="col-md-12 text-center">
    <div class="card-body">
      Mínimo: $<%=  number_with_delimiter(min, delimiter: ".", separator: "," )  %> |
      Máximo:  $<%=  number_with_delimiter(max, delimiter: ".", separator: "," ) %> |
      Media: $<%=  number_with_delimiter('%.2f' % avg, delimiter: ".", separator: ",", precision: 2 ) %>
    </div>
  </div>
</div>

<% if @tmcs %>
  <div class="row my-md-5 card">
    <div class="col-md-12 card-body">
      <h4> TMCs</h4>
      <%= line_chart @tmcs, thousands: ".", decimal: ",", legend: "TMCs", xtitle: "Período", ytitle: "Tasa", suffix: "%" %>
      <% stats = tmc_stats(@tmcs) %>
      <div class="col-md-12 my-md-5 card">
        <div class="text-left"></div>
        <strong>Tasa Máxima para cada tipo de préstamo en este período:</strong>
        <ul class="list-group">
          <% stats.each do |tmc_info| %>
            <li class="list-group-item">
              <div class="row">
                <div class="col-md-11">
                <small><%= tmc_info[:name] %></small>
                </div>
                <div class="col-md-1">
                 <%= tmc_info[:max] %>%
                </div>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% else %>
 <div class="row my-md-5 card">
    <div class="col-md-12 card-body text-center">
      No se encontraron datos para TMCs en el período
    </div>
  </div>
<% end %>

<div class="row my-md-5">
  <div class="col-md-12 text-center">
    <%= link_to t(:back), root_path, class: "btn btn-success" %>
  </div>
</div>